package adr

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// IndexPath is the generated index, relative to the shared root.
var IndexPath = filepath.Join(Dir, "README.md")

// Index renders docs/adr/README.md from the full record set.
//
// Deterministic in the record set alone, which is what makes concurrent writes
// safe: every session regenerates the same bytes, so last-write-wins is correct
// rather than merely tolerated (prd §5.2).
func Index(recs []*Record) []byte {
	sorted := make([]*Record, len(recs))
	copy(sorted, recs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID > sorted[j].ID }) // newest first

	var b strings.Builder
	b.WriteString("# Decision records\n\n")
	b.WriteString("<!-- Generated by `dlog index`. Do not edit by hand. -->\n\n")

	if len(sorted) == 0 {
		b.WriteString("No records yet. `dlog new \"<title>\"` writes the first one.\n")
		return []byte(b.String())
	}

	b.WriteString("| Record | Status | Date | Tags |\n|---|---|---|---|\n")
	for _, r := range sorted {
		fmt.Fprintf(&b, "| [%s](%s.md) | %s | %s | %s |\n",
			escapePipes(r.Title), r.ID, r.Status, r.Date, escapePipes(strings.Join(r.Tags, ", ")))
	}

	// The graph is a DAG, not a tree: parallel sessions converge and multiple
	// parents are normal (prd §5.3).
	node := map[string]string{}
	for i, r := range sorted {
		node[r.ID] = fmt.Sprintf("n%d", i)
	}
	var edges []string
	for _, r := range sorted {
		for _, dep := range r.DependsOn {
			if t, ok := node[dep]; ok {
				edges = append(edges, fmt.Sprintf("  %s --> %s", node[r.ID], t))
			}
		}
		for _, sup := range r.Supersedes {
			if t, ok := node[sup]; ok {
				edges = append(edges, fmt.Sprintf("  %s -. supersedes .-> %s", node[r.ID], t))
			}
		}
	}

	b.WriteString("\n## Graph\n\n```mermaid\ngraph TD\n")
	for _, r := range sorted {
		fmt.Fprintf(&b, "  %s[%q]\n", node[r.ID], truncate(r.Title, 60))
	}
	sort.Strings(edges)
	for _, e := range edges {
		b.WriteString(e + "\n")
	}
	for _, r := range sorted {
		if r.Status == "superseded" || r.Status == "rejected" || r.Status == "reverted" {
			fmt.Fprintf(&b, "  style %s stroke-dasharray: 4\n", node[r.ID])
		}
	}
	b.WriteString("```\n")
	return []byte(b.String())
}

// WriteIndex regenerates the index on disk.
func WriteIndex(root string, recs []*Record) error {
	path := filepath.Join(root, IndexPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, Index(recs), 0o644)
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}
